# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  ############## INITIALIZE #################

  before_all do
      ENV["FIREBASE_TOKEN"] = "1//09haJ-T_OeeFjCgYIARAAGAkSNwF-L9IrnMB610hJKNzUeWMB0xQQJHh5t2aFGEvtgHnGHBeMCHTtvee9sRWBlJ3gVHlYsh7_9v0"
      # sh("git fetch")
  end

    ############### START TEST ################

  desc "Runs all the tests"
    lane :test do
      gradle(task: "test")
    end

  desc "Runs all the Unit Tests on Release variant"
  lane :unitTests do
    gradle(task: "runUnitTests")
  end

  desc "Runs all the Instrumented(Android) Tests on Release and Debug variants. An android device has to be connected."
  lane :androidTests do
    gradle(task: "runAndroidTests")
  end

  desc "Runs all Unit Tests and Android Tests. An android device has to be connected."
  lane :allTests do
    gradle(task: "runAllTests")
  end

    ############## UPLOAD TO FIREBASE APP DISTRIBUTION #################

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do
    # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
    # To get a list of all available parameters for the gradle action, run: fastlane action gradle
    # gradle(task: "clean assembleRelease")
    gradle(
        task: 'assemble',
        build_type: 'Release'
      )
    firebase_app_distribution(
        app: "1:1087940686958:android:64e91bdf7064a92bb6627f",
        groups: "qa-team"
      )

    # sh "your_script.sh"
    # ...
  end

    ############## UPLOAD TO GOOGLE PLAY #################

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

end
